# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DaddyTrap's Blog
email: daddytrapc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks to jekyll, it is easy for me to build such an awesome blog!
  I will post some articles about some techniques or something else.
  I hope I will write more valuable articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daddytrap.github.io" # the base hostname & protocol for your site
github_username:  DaddyTrap

# Build settings
markdown: kramdown
