title: DaddyTrap's Blog
description: Used as a blog or a playground.

url: "https://daddytrap.github.io"
github_username: DaddyTrap
email: daddytrapc@gmail.com
theme: jekyll-theme-cayman
repository: DaddyTrap/daddytrap.github.io

exclude: ['LICENSE', 'Rakefile', 'jekyll-theme-cayman.gemspec', 'README.md', 'Gemfile', 'Gemfile.lock']

github: [metadata]